/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_d91f8206 (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/lompxaggrcfmmsjkbgyt/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

const client = () => createClient(
  Deno.env.get("SUPABASE_URL"),
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),
);

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_d91f8206").upsert({
    key,
    value
  });
  if (error) {
    throw new Error(error.message);
  }
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<any> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_d91f8206").select("value").eq("key", key).maybeSingle();
  if (error) {
    throw new Error(error.message);
  }
  return data?.value;
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_d91f8206").delete().eq("key", key);
  if (error) {
    throw new Error(error.message);
  }
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_d91f8206").upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
  if (error) {
    throw new Error(error.message);
  }
};

// Gets multiple key-value pairs from the database.
export const mget = async (keys: string[]): Promise<any[]> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_d91f8206").select("value").in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_d91f8206").delete().in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
};

// Search for key-value pairs by prefix.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_d91f8206").select("key, value").like("key", prefix + "%");
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};

// Atomically increment a numeric KV value. Uses an optimistic compare-and-swap loop.
export const increment = async (key: string, maxRetries = 12): Promise<number> => {
  const supabase = client();

  for (let attempt = 0; attempt < maxRetries; attempt++) {
    // Read current value (could be undefined)
    const { data: readData, error: readError } = await supabase
      .from('kv_store_d91f8206')
      .select('value')
      .eq('key', key)
      .maybeSingle();

    if (readError) {
      throw new Error(readError.message);
    }

    let current = readData?.value;

    // If no row exists, try to insert initial value 1
    if (current === undefined || current === null) {
      const { error: insertError } = await supabase
        .from('kv_store_d91f8206')
        .insert([{ key, value: 1 }]);

      if (!insertError) {
        return 1;
      }

      // If insert failed (likely conflict), loop and retry
      await new Promise((r) => setTimeout(r, 50 * (attempt + 1)));
      continue;
    }

    // Ensure numeric
    const currentNum = typeof current === 'number' ? current : Number(current);
    if (Number.isNaN(currentNum)) {
      throw new Error(`KV value for ${key} is not a number`);
    }

    const newVal = currentNum + 1;

    // Try optimistic update: update only if value matches the one we read
    const { data: updateData, error: updateError } = await supabase
      .from('kv_store_d91f8206')
      .update({ value: newVal })
      .match({ key, value: current });

    if (updateError) {
      // If update failed, retry
      await new Promise((r) => setTimeout(r, 50 * (attempt + 1)));
      continue;
    }

    // If updateData is non-empty, we succeeded
    if (updateData && (Array.isArray(updateData) ? updateData.length > 0 : true)) {
      return newVal;
    }

    // Otherwise, another process changed the value before us; retry with backoff
    await new Promise((r) => setTimeout(r, 50 * (attempt + 1)));
  }

  throw new Error(`Failed to increment key ${key} after ${maxRetries} attempts`);
};