// Supabase configuration - embedded at build time for Vercel
export const supabaseConfig = {
  projectId: 'lompxaggrcfmmsjkbgyt',
  anonKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvbXB4YWdncmNmbW1zamtiZ3l0Iiwicm9zZSI6ImFub24iLCJpYXQiOjE3NzM3ODc3MDQsImV4cCI6MjA4OTM2MzcwNH0.3i1MYKC1yTRfgmyf_9_BvkeG4fxnFeYTvDxRfzkL1oM',
  serviceRoleKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZmaG93d3ZseXRub3VsaWpjbGFjIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjA1ODA5MCwiZXhwIjoyMDg3NjM0MDkwfQ.D5pdck32n7bYCsfjIgGlDubfHKIhnnJkNCpSbpd_ASQ',
};
